ALTER TABLE proveedores 
ADD COLUMN IF NOT EXISTS ciudad VARCHAR(100),
ADD COLUMN IF NOT EXISTS pais VARCHAR(100) DEFAULT 'Colombia',
ADD COLUMN IF NOT EXISTS codigo VARCHAR(50),
ADD COLUMN IF NOT EXISTS especialidades TEXT,
ADD COLUMN IF NOT EXISTS tiempo_entrega_dias INT DEFAULT 7;
